### ISSUE TITLE
405 (method not allowed) when calling get_analysis()

### ISSUE THREAD

**Issue by phretor** [Koodous/python-sdk#3]
```python
In [1]: from koodous import Koodous

In [2]: Koodous('MY_TOKEN').get_analysis(
    '79a3bc6da45243355a920082dc67da0febf19379c25c721c43fd6b3f83ff4ef4')

In [3]: 
```

`None` is returned. Further investigation reveals that [L142](https://github.com/Koodous/python-sdk/blob/master/koodous/koodous.py#L142) contains an empty response with status code 405.

The sample exists: https://koodous.com/apks/79a3bc6da45243355a920082dc67da0febf19379c25c721c43fd6b3f83ff4ef4

**Comment by plutec** [comment]
If a sample is not analyzed the API response an empty json with 405 status code. I will raise an exception when this occurs better than return None.

**Comment by phretor** [comment]
The only thing I don't agree with is the status code. 405 is conceptually different from 404.

**Comment by plutec** [comment]
Yes, 404 is when an APK doesn't exist (it's logical) and 405 when the analysis is not ready. It is the best way that we thought in its moment.
